### ISSUE TITLE
🚀 [REQUEST] - deprecate default in-file name

### ISSUE THREAD

**Issue by c33s** [carlocorradini/inline#10]
### Summary

what do you think of deprecating the default name for the input-file and name the output-file something like `original-script-name.inlined.sh`?

could be more intuitive when running the command without parameter, which currently lead to `script.sh not found` instead of the help/usage screen.

### Basic Example

-

**Comment by carlocorradini** [comment]
Nice enhancement 🥳

**Comment by carlocorradini** [comment]
@c33s See PR #11 🥳

**Comment by carlocorradini** [comment]
@c33s Any thoughts on PR #11

**Comment by c33s** [comment]
sorry for the delay. looks good to me (haven't tested it yet).

just another thought i had: if you want to keep the default script name as extra you could allow the user to export a specific environment variable like `INLINE_DEFAULT_IN_SCRIPT_NAME=script.sh`. i personally don't require that feature, it was just an idea for allowing the keep the "old" behavior.

**Comment by carlocorradini** [comment]
Nah. I think what you've suggested is the best approach. 🥳
