### ISSUE TITLE
🐛 [BUG] - readlink: unrecognized option: m

### ISSUE THREAD

**Issue by c33s** [carlocorradini/inline#7]
### Description

running the script on alpine/busybox fails with the following error:
```
readlink: unrecognized option: m
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

        -f      Canonicalize by following all symlinks
        -n      Don't add newline
        -v      Verbose
```

### Reproduction steps

```sh
on `alpine:3.17.0` run:

bash inline.sh --in-file test.sh
```
`test.sh`
```
#!/bin/ash

echo "hello"
source header.sh
```

`header.sh`
```
# fail on non-zero exit code
set -e -o pipefail -o errexit
```

### OS

Alpine Linux Busybox

hopefully helpful links:
- https://github.com/basherpm/basher/issues/49
- https://github.com/BernieO/calcardbackup/issues/4

**Comment by carlocorradini** [comment]
@c33s See PR #8 
Let me know what you think 🥳

PS: *Merry Christmas*

**Comment by c33s** [comment]
that was a really fast! awesome :)
looks good to me. tested it on my alpine box. . thank you very much.

merry x-mas :)
