### ISSUE TITLE
🚀 [REQUEST] - source from cwd or from sourced script

### ISSUE THREAD

**Issue by c33s** [carlocorradini/inline#9]
just to share my thoughts, having a folder structure like that:
```
├── bin
│   └── main.sh
            source templates/test/a.sh
└── templates
    └── test
        ├── a.sh
                echo this is a
                source templates/test/b.sh # required for regular bash script usage
                vs
                source b.sh # required with inline.sh
        └── b.sh
                echo this is b
```
and running `main.sh` from the root dir leads to an error like:
```
bash bin/main.sh
...
[FATAL] Unable to resolve source file path ...
[FATAL] Error inlining file ...
```

it works if `source` is used without path but then the usage breaks if i want to run it with a native bash call and vice versa.

some option like `--relative-sourcing` vs `--source-from-cwd` could be helpful

**Comment by carlocorradini** [comment]
You can use `shellcheck source=PATH/TO/SCRIPT` on the line just before `source templates/test/a.sh"` in `main.sh`. Because they could lead to misunderstandings, I do not want to include relative sourcing or cwd.
Additionally, since `shellcheck` is well known and widely used, I wish to utilize a similar approach (static analysis or something similar).
Update `main.sh`:
```sh
# shellcheck source=../templates/test/a.sh
source templates/test/a.sh
```

However, if you believe that `cwd` sourcing is utilized *a lot* and is a truly useful feature, we can discuss it.
I don't want my opinion to take precedence over others simply because I am the keeper.

**Comment by c33s** [comment]
i haven't used shellcheck in that way. i will give it a try but i am not sure i understand how the shellcheck annotation will help the `source` command find the correct path if i call the script normally via bash. 

> source
> Tell ShellCheck where to find a sourced file (since 0.4.0):

https://www.shellcheck.net/wiki/Directive

if i assume that my dir tree shown above is in `~/test-project`:
```
cd ~/test-project
bash bin/main.sh
```
to make this call work i would need to  use `source templates/test/a.sh` in `main.sh`. how would the shellcheck annotation help?
or did you mean you think about integrating such a feature with the shellcheck annotation?

in my bash scripts i often use this hack to allow calls from everywhere to the script:
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/lib/functions.sh"
source "${DIR}/lib/colors.sh"
```
in this case all of the following works:
```
cd ~ && bash bin/main.sh
cd / && bash bin/main.sh
cd ~/test-project && bash bin/main.sh
cd ~/test-project/bin && bash bin/main.sh
```

**Comment by carlocorradini** [comment]
Yes. However, both my script and shellcheck are static tools that do not execute your script to evaluate dynamically what is `${DIR}` in `source`. Therefore, you can continue using your approach. Update `source` (that fails) with a simple comment before `source`. Whenever `inline` finds a `# shellcheck source=PATH_TO_SCRIPT` before `source`, save `PATH_TO_SCRIPT` to a temporary variable. If it fails to resolve `source PATH_TO_SCRIPT` as a normal import, it falls back to shellcheck's PATH_TO_SCRIPT.

**Comment by carlocorradini** [comment]
Simpler: If I try to resolve a path with a variable it fails (if not in PATH) because the value (Dynamic) is unknown. Therefore, you need to add a hint to correctly resolve the source path.
